### ISSUE TITLE
cant run after installation

### ISSUE THREAD

**Issue by nader119376** [merkinmuffley/mixmaster4096#10]
mixmaster: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
![screenshot from 2018-04-15 03-22-25](https://user-images.githubusercontent.com/36439894/38773991-742141fc-405c-11e8-9775-64c6f3d12761.png)

**Comment by merkinmuffley** [comment]
/etc/os-release    
     1  PRETTY_NAME="Debian GNU/Linux 8 (jessie)"  
     2  NAME="Debian GNU/Linux"  
     3  VERSION_ID="8"  
     4  VERSION="8 (jessie)"  
     5  ID=debian  
     6  HOME_URL="http://www.debian.org/"  
     7  SUPPORT_URL="http://www.debian.org/support"  
     8  BUG_REPORT_URL="https://bugs.debian.org/"  


$ ldd /usr/bin/mixmaster  
        linux-vdso.so.1 (0x00007fff4539a000)  
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f1d102cd000)  
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f1d100b2000)  
        libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007f1d0fe44000)  
 >>>    libcrypto.so.1.0.0 => /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.0 (0x00007f1d0fa47000)  
        libncurses.so.5 => /lib/x86_64-linux-gnu/libncurses.so.5 (0x00007f1d0f822000)  
        libtinfo.so.5 => /lib/x86_64-linux-gnu/libtinfo.so.5 (0x00007f1d0f5f8000)  
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f1d0f24d000)  
        /lib64/ld-linux-x86-64.so.2 (0x00007f1d104d1000)  
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f1d0f030000)  


NEED PACKAGE libssl1.0.0:amd64

**Comment by nader119376** [comment]
thanks for reply! 

this is mine 
![screenshot from 2018-04-15 06-15-30](https://user-images.githubusercontent.com/36439894/38775012-8ed793f6-4076-11e8-9ade-cdb7d2b039a2.png)

i had setup this package
libssl1.0.0_1.0.1t-1+deb8u8_amd64.deb

then every thing works fine 

but when i sent the message it always shows me this without recieving any email yet
![screenshot from 2018-04-15 06-29-39](https://user-images.githubusercontent.com/36439894/38775018-ce65042c-4076-11e8-99df-ee626fbe816d.png)

i have not setup any email services like postfix , sendmail or qmail

any help?

**Comment by merkinmuffley** [comment]
To use a remailer you need to have mail transport.   

Are you a) trying to run a remailer;   or b) just trying to use a remailer client (send mail) ?

**Comment by nader119376** [comment]
im sorry i dont know the difference

need is to be able to send an anonymous email without being traced, and my ip will not be shown in the email headers

thats all i want

can i do this?

**Comment by merkinmuffley** [comment]
To send mail you have to be able to send mail.    Set up a a mail transfer agent such as postfix.    

Once you can send traceable mail load your mixmaster with recent stats  (pick option u , then mixmin).  Then you can create encrypted mail that will be sent to the remailer network and eventually arrive untraceable somewhere.     

If you want a reply to mail that's untraceable (I'd assume at least a few major governments can trace it) your message should include some directions on replying in a public place that you can read without attracting attention.   If you just need to tell some guy in your office that he smells you can probably do without a reply.
